### ISSUE TITLE
A very bad idea in the UINavigation category !!!!

### ISSUE THREAD

**Issue by nverinaud** [mikefrederick/MFSideMenu#38]
This lib completely destroy the way navigation controllers work.

You are redefining UINavigationController appearance callbacks which is a really bad thing.
When you redefine a method in a category you completely replace this method with your own, it's not like inheritance where you have access to the super implementation.

To illustrate, consider the following code from `UINavigationController+MFSideMenu.m`:

```
- (void) viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];

    [self.sideMenu performSelector:@selector(navigationControllerWillAppear)];
}
```

Calling `[super viewWillAppear:animated]` here will call `-[UIViewController viewWillAppear:]` and not `-[UINavigationController viewWillAppear:]`.
I think many issues, particularly in iOS 5, are due to this bad design.

An option would be to create a UINavigationController subclass or use delegation.

**Comment by fabiosoft** [comment]
have you some alternative? I mean...what other control con you advice to developer who want to add a side menu to their app? I tried MFSideMenu and it works pretty well...you know the very "best" control i can use in alternative?

**Comment by mikefrederick** [comment]
@nverinaud you're right, that was a poor design, I don't know how I missed that. I will refactor it when I get a chance.

**Comment by nverinaud** [comment]
@fabiosoft I suggest you my solution available here : http://www.cocoacontrols.com/platforms/ios/controls/nvslidemenucontroller. Or you can try John Luch's one available here : http://www.cocoacontrols.com/platforms/ios/controls/swrevealviewcontroller. The two requires iOS 5+ and mine is not ARC compatible.

**Comment by mikefrederick** [comment]
I have already implemented a fix for this, but it hasn't been pushed to the repo yet, so don't let this chase you away.

**Comment by chilloutman** [comment]
Will you push it soon? The category breaks all viewWillAppear and similar events for all UINavigationControllers in my app. The events don't propagate to the rootViewController of the navigation controller and causes all sorts of issues. I can't use it like this.

**Comment by chilloutman** [comment]
Any news on when the fix will be made available?

**Comment by fabiosoft** [comment]
an update was released less than a month ago.... i use and i love this control! :)

**Comment by chilloutman** [comment]
The file has not been changed in the last 3 months and I can see the override is still inside the UINavigationController-category. The problem is still there.
https://github.com/mikefrederick/MFSideMenu/blob/master/MFSideMenuDemo/MFSideMenu/UINavigationController%2BMFSideMenu.m

**Comment by nverinaud** [comment]
Poke @mikefrederick to release his update...

**Comment by mikefrederick** [comment]
Sorry guys, I am trying to figure out the best solution for the issue, I will have a fix soon.

**Comment by inPhilly** [comment]
Has this been fixed yet?

**Comment by gonecoding** [comment]
I used namespaced versions of the overwritten methods in the UINavigationController category and swizzled the implementations in the designated initializer. Seems to work fine for me after a quick check. The -viewDidAppear on one of my view controllers is now being called again. Have not thoroughly tested this though.

**Comment by mikefrederick** [comment]
I considered doing a swizzle as a temporary fix. Really not a fan of method swizzling but since I haven't had a chance to implement a permanent fix yet, @gonecoding will you submit a pull request?

**Comment by gonecoding** [comment]
Yeah, not a big fan of swizzling myself. Makes code harder to maintain. Another possibility to approach this would be to create an MFNavigationController class that users would have to subclass.

I'll submit a pull request as soon as I find out how to do that while including only one commit... :)
